services:
  db-aqua-gloss-pro:
    image: postgres:17-alpine
    container_name: db-aqua-gloss-pro-container
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api-aqua-gloss-pro:
    build: .
    container_name: api-aqua-gloss-pro-container
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db-aqua-gloss-pro
volumes:
  postgres_data:
